/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FTShop;

/**
 *
 * @author ADMIN
 */
import Connection.MySQLConnect;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.print.PrinterException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.*;
import java.text.MessageFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.security.auth.login.LoginContext;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class FTShop extends javax.swing.JFrame {
    private static final String Username = "root";
    private static final String Password = "123456789";
    private static final String Dataconn =  "jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false";
    
    Connection sqlconn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q,i;
    
    /**
     * Creates new form FTShop
     */
    public FTShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //========================function=================================
    public void upDateDB(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlconn = DriverManager.getConnection(Dataconn, Username,Password);
            pst = sqlconn.prepareStatement("Select * from sanpham");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q =stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
                
            while(rs.next()){
                Vector columnData = new Vector();
                
                for (i = 1; i<=q;i++){
                    columnData.add(rs.getString("ma_san_pham"));
                    columnData.add(rs.getString("ten_san_pham"));
                    columnData.add(rs.getString("gia_san_pham"));
                    columnData.add(rs.getString("mo_ta_san_pham"));
                    columnData.add(rs.getString("mau_sac"));
                    columnData.add(rs.getString("ma_loai_san_pham"));
                }
                    RecordTable.addRow(columnData);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }
    
    
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jtxtidtypeproduct = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtidproduct = new javax.swing.JTextField();
        jtxtnameproduct = new javax.swing.JTextField();
        jtxtprice = new javax.swing.JTextField();
        jtxtdiscribe = new javax.swing.JTextField();
        jtxtcolor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        JbtnExitftshop = new javax.swing.JButton();
        jbtnaddnew = new javax.swing.JButton();
        jbtnupdate = new javax.swing.JButton();
        jbtnprint = new javax.swing.JButton();
        Jbtnreset = new javax.swing.JButton();
        Jbtndelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jbtnsearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 8, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 8, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDProduct", "NameProduct", "Price", "Discribe", "Color", "IDTypeProduct"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 740, 130));

        jLabel6.setText("IDTypeProduct");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 20));
        jPanel2.add(jtxtidtypeproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 420, 30));

        jLabel9.setText("IDProduct");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 20));

        jLabel10.setText("NameProduct");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));

        jLabel11.setText("Price");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 20));

        jLabel12.setText("Discribe");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, 20));

        jLabel13.setText("color");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 20));
        jPanel2.add(jtxtidproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 420, 30));
        jPanel2.add(jtxtnameproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 420, 30));
        jPanel2.add(jtxtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 420, 30));
        jPanel2.add(jtxtdiscribe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 420, 30));
        jPanel2.add(jtxtcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 420, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 760, 400));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 8, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbtnExitftshop.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JbtnExitftshop.setText("Exit");
        JbtnExitftshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnExitftshopActionPerformed(evt);
            }
        });
        jPanel3.add(JbtnExitftshop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 50));

        jbtnaddnew.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnaddnew.setText("Add new ");
        jbtnaddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddnewActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnaddnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 50));

        jbtnupdate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnupdate.setText("Update");
        jbtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, 50));

        jbtnprint.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnprint.setText("Print");
        jbtnprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnprintMouseClicked(evt);
            }
        });
        jbtnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnprintActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 50));

        Jbtnreset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Jbtnreset.setText("Reset");
        Jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnresetActionPerformed(evt);
            }
        });
        jPanel3.add(Jbtnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 50));

        Jbtndelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Jbtndelete.setText("Delete");
        Jbtndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtndeleteActionPerformed(evt);
            }
        });
        jPanel3.add(Jbtndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 220, 400));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        jLabel1.setText("FTShop");

        Jbtnsearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Jbtnsearch.setText("Search");
        Jbtnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(Jbtnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Jbtnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 980, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnaddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddnewActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlconn = DriverManager.getConnection(Dataconn,Username,Password);
            pst = sqlconn.prepareStatement("insert into sanpham(ma_san_pham,ten_san_pham,gia_san_pham,mo_ta_san_pham,mau_sac,ma_loai_san_pham) value (?,?,?,?,?,?)");
            
            pst.setString(1, jtxtidproduct.getText());
            pst.setString(2, jtxtnameproduct.getText());
            pst.setString(3, jtxtprice.getText());
            pst.setString(4, jtxtdiscribe.getText());
            pst.setString(5, jtxtcolor.getText());
            pst.setString(6, jtxtidtypeproduct.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            upDateDB();
            
        }catch(ClassNotFoundException ex){
            Logger.getLogger(FTShop.class.getName()).log(Level.SEVERE, null, ex);
        }catch(SQLException ex){
            Logger.getLogger(FTShop.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }//GEN-LAST:event_jbtnaddnewActionPerformed
private JFrame frame;
    private void JbtnExitftshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnExitftshopActionPerformed
        // TODO add your handling code here:
       frame = new  JFrame("Exit");
       if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","MySQL Connector",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
           System.exit(0);
       }
    }//GEN-LAST:event_JbtnExitftshopActionPerformed

    private void JbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnresetActionPerformed
        // TODO add your handling code here:
        jtxtcolor.setText("");
        jtxtdiscribe.setText("");
        jtxtidproduct.setText("");
        jtxtidtypeproduct.setText("");
        jtxtnameproduct.setText("");
        jtxtprice.setText("");
        
    }//GEN-LAST:event_JbtnresetActionPerformed

    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlconn = DriverManager.getConnection(Dataconn,Username,Password);
            pst = sqlconn.prepareStatement("update sanpham set ma_san_pham=?, ten_san_pham=?, gia_san_pham=?, mo_ta_san_pham=?, mau_sac=?, ma_loai_san_pham=? where ma_san_pham=?");
            
            pst.setString(1, jtxtidproduct.getText());
            pst.setString(2, jtxtnameproduct.getText());
            pst.setString(3, jtxtprice.getText());
            pst.setString(4, jtxtdiscribe.getText());
            pst.setString(5, jtxtcolor.getText());
            pst.setString(6, jtxtidtypeproduct.getText());
            
            
            JOptionPane.showMessageDialog(this, "Record Updated");
            upDateDB();
            
        }catch(ClassNotFoundException ex){
            Logger.getLogger(FTShop.class.getName()).log(Level.SEVERE, null, ex);
        }catch(SQLException ex){
            Logger.getLogger(FTShop.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jbtnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnprintActionPerformed
        
    }//GEN-LAST:event_jbtnprintActionPerformed

    private void jbtnprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnprintMouseClicked
       MessageFormat header  = new MessageFormat("Printing in progress");
       MessageFormat footer = new MessageFormat("Page{0,number,integer}");
       
       try{
           jTable1.print(JTable.PrintMode.NORMAL,header,footer);
       } catch (java.awt.print.PrinterException e) {
           System.err.format("No Printer found", e.getMessage())    ;
        }
    }//GEN-LAST:event_jbtnprintMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
            
        jtxtidproduct.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        jtxtnameproduct.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        jtxtprice.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        jtxtdiscribe.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        jtxtcolor.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        jtxtidtypeproduct.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void JbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtndeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try{  
            
            CallableStatement csmt = null;
            int deleteItem = JOptionPane.showConfirmDialog(null, "confirm if you want to delete item", "Warning", JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                sqlconn = DriverManager.getConnection(Dataconn,Username,Password);
                csmt = sqlconn.prepareCall("{call sp_DeleteProduct(?,?)}");
                
                csmt.setString(1, jtxtidproduct.getText());
                csmt.setString(2, jtxtnameproduct.getText());
                csmt.executeUpdate();
                csmt.close();
                JOptionPane.showMessageDialog(this, "Record updated");
                upDateDB();
                
                jtxtidproduct.setText("");
                jtxtprice.setText("");
                jtxtnameproduct.setText("");
                jtxtdiscribe.setText("");
                jtxtcolor.setText("");
                jtxtidtypeproduct.setText("");
            }      
        }catch(ClassNotFoundException ex){
            Logger.getLogger(FTShop.class.getName()).log(Level.SEVERE, null, ex);
        }catch(SQLException ex){
            Logger.getLogger(FTShop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JbtndeleteActionPerformed

    private void JbtnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnsearchActionPerformed
    new Search_SP().setVisible(true);
    }//GEN-LAST:event_JbtnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new sign_log.SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnExitftshop;
    private javax.swing.JButton Jbtndelete;
    private javax.swing.JButton Jbtnreset;
    private javax.swing.JButton Jbtnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnaddnew;
    private javax.swing.JButton jbtnprint;
    private javax.swing.JButton jbtnupdate;
    private javax.swing.JTextField jtxtcolor;
    private javax.swing.JTextField jtxtdiscribe;
    private javax.swing.JTextField jtxtidproduct;
    private javax.swing.JTextField jtxtidtypeproduct;
    private javax.swing.JTextField jtxtnameproduct;
    private javax.swing.JTextField jtxtprice;
    // End of variables declaration//GEN-END:variables
}
